2020-08-13 23:27:43,172 : INFO : Start of Prediction
2020-08-13 23:27:43,172 : INFO : run_id:2020-08-13_232743_625991148
2020-08-13 23:27:43,172 : INFO : Start of Data Load, validation and transformation
2020-08-13 23:27:43,173 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 23:27:43,173 : INFO : End of Archiving Old Rejected Files...
2020-08-13 23:27:43,173 : INFO : Start of Archiving Old Validated Files...
2020-08-13 23:27:43,175 : INFO : End of Archiving Old Validated Files...
2020-08-13 23:27:43,175 : INFO : Start of Archiving Old Processed Files...
2020-08-13 23:27:43,178 : INFO : End of Archiving Old Processed Files...
2020-08-13 23:27:43,179 : INFO : Start of Archiving Old Result Files...
2020-08-13 23:27:43,180 : INFO : End of Archiving Old Result Files...
2020-08-13 23:27:43,180 : INFO : Start of Reading values From Schema...
2020-08-13 23:27:43,180 : INFO : End of Reading values From Schema...
2020-08-13 23:27:43,180 : INFO : Start of Validating Column Length...
2020-08-13 23:27:43,191 : INFO : End of Validating Column Length...
2020-08-13 23:27:43,191 : INFO : Start of Validating Missing Values...
2020-08-13 23:27:43,199 : INFO : End of Validating Missing Values...
2020-08-13 23:27:43,199 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 23:27:43,238 : INFO : Credit_Approval_predict_data.csv: File Transformed successfully!!
2020-08-13 23:27:43,238 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 23:27:43,238 : INFO : Start of Creating Table...
2020-08-13 23:27:43,257 : INFO : Opened prediction database successfully
2020-08-13 23:27:43,430 : INFO : CREATE TABLE prediction_raw_data_t column_name
2020-08-13 23:27:43,559 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:43,665 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:43,787 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:43,896 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:43,962 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,094 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,195 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,280 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,379 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,473 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,555 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,720 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:44,879 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:45,023 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 23:27:45,024 : INFO : End of Creating Table...
2020-08-13 23:27:45,026 : INFO : Opened prediction database successfully
2020-08-13 23:27:45,026 : INFO : Start of Inserting Data into Table...
2020-08-13 23:27:45,160 : INFO : End of Inserting Data into Table...
2020-08-13 23:27:45,160 : INFO : Start of Exporting Data into CSV...
2020-08-13 23:27:45,161 : INFO : Opened prediction database successfully
2020-08-13 23:27:45,163 : INFO : End of Exporting Data into CSV...
2020-08-13 23:27:45,163 : INFO : Start of Moving Processed Files...
2020-08-13 23:27:45,165 : INFO : Moved the already processed file Credit_Approval_predict_data.csv
2020-08-13 23:27:45,165 : INFO : End of Moving Processed Files...
2020-08-13 23:27:45,165 : INFO : End of Data Load, validation and transformation
2020-08-13 23:27:45,165 : INFO : Start of Preprocessing...
2020-08-13 23:27:45,165 : INFO : Start of reading dataset...
2020-08-13 23:27:45,175 : INFO : End of reading dataset...
2020-08-13 23:27:45,175 : INFO : Start of Droping Columns...
2020-08-13 23:27:45,177 : INFO : End of Droping Columns...
2020-08-13 23:27:45,177 : INFO : Start of replacing invalid values...
2020-08-13 23:27:45,199 : INFO : end of replacing invalid values...
2020-08-13 23:27:45,199 : INFO : Start of encode Categorical Values ...
2020-08-13 23:27:45,208 : INFO : end of encode Categorical Values...
2020-08-13 23:27:45,208 : INFO : Start of feature encoding...
2020-08-13 23:27:45,249 : INFO : End of feature encoding...
2020-08-13 23:27:45,263 : INFO : Start of Droping Columns...
2020-08-13 23:27:45,265 : INFO : End of Droping Columns...
2020-08-13 23:27:45,265 : INFO : Start of finding missing values...
2020-08-13 23:27:45,266 : INFO : End of finding missing values...
2020-08-13 23:27:45,267 : INFO : Start feature selection of dataset...
2020-08-13 23:27:45,274 : INFO : End feature selection of dataset...
2020-08-13 23:27:45,274 : INFO : Start of building final predictset...
2020-08-13 23:27:45,294 : INFO : End of building final predictset...
2020-08-13 23:27:45,294 : INFO : End of Preprocessing...
2020-08-13 23:27:45,294 : INFO : Start of Load Model
2020-08-13 23:27:45,294 : ERROR : Exception raised while Loading Model: [Errno 2] No such file or directory: 'apps/models/apps/models/apps/models.sav'
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\core\file_operation.py", line 71, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/apps/models/apps/models.sav'
2020-08-13 23:27:45,306 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\core\file_operation.py", line 71, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/apps/models/apps/models.sav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\prediction\predict_model.py", line 50, in batch_predict_from_model
    model = self.fileOperation.load_model(XGB)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\core\file_operation.py", line 77, in load_model
    raise Exception()
Exception
