2020-08-12 10:06:26,920 : INFO : Start of Training
2020-08-12 10:06:26,920 : INFO : Run_id:2020-08-12_100626_415728862
2020-08-12 10:06:26,920 : INFO : Start of Data Load, validation and transformation
2020-08-12 10:06:26,920 : INFO : Start of Archiving Old Rejected Files...
2020-08-12 10:06:26,921 : INFO : End of Archiving Old Rejected Files...
2020-08-12 10:06:26,921 : INFO : Start of Archiving Old Validated Files...
2020-08-12 10:06:26,924 : INFO : End of Archiving Old Validated Files...
2020-08-12 10:06:26,924 : INFO : Start of Archiving Old Processed Files...
2020-08-12 10:06:26,925 : INFO : End of Archiving Old Processed Files...
2020-08-12 10:06:26,925 : INFO : Start of Archiving Old Result Files...
2020-08-12 10:06:26,926 : INFO : End of Archiving Old Result Files...
2020-08-12 10:06:26,926 : INFO : Start of Reading values From Schema...
2020-08-12 10:06:26,926 : INFO : End of Reading values From Schema...
2020-08-12 10:06:26,926 : INFO : Start of Validating Column Length...
2020-08-12 10:06:26,927 : INFO : End of Validating Column Length...
2020-08-12 10:06:26,927 : INFO : Start of Validating Missing Values...
2020-08-12 10:06:26,927 : INFO : End of Validating Missing Values...
2020-08-12 10:06:26,927 : INFO : Start of Replacing Missing Values with NULL...
2020-08-12 10:06:26,927 : INFO : End of Replacing Missing Values with NULL...
2020-08-12 10:06:26,927 : INFO : Start of Creating Table...
2020-08-12 10:06:26,928 : INFO : Opened training database successfully
2020-08-12 10:06:26,928 : INFO : Tables created successfully
2020-08-12 10:06:26,928 : INFO : Closed training database successfully
2020-08-12 10:06:26,928 : INFO : End of Creating Table...
2020-08-12 10:06:26,929 : INFO : Opened training database successfully
2020-08-12 10:06:26,929 : INFO : Start of Inserting Data into Table...
2020-08-12 10:06:26,929 : INFO : End of Inserting Data into Table...
2020-08-12 10:06:26,929 : INFO : Start of Exporting Data into CSV...
2020-08-12 10:06:26,930 : INFO : Opened training database successfully
2020-08-12 10:06:26,943 : INFO : End of Exporting Data into CSV...
2020-08-12 10:06:26,945 : INFO : Start of Moving Processed Files...
2020-08-12 10:06:26,945 : INFO : End of Moving Processed Files...
2020-08-12 10:06:26,945 : INFO : End of Data Load, validation and transformation
2020-08-12 10:06:26,946 : INFO : Start of Preprocessing...
2020-08-12 10:06:26,946 : INFO : Start of reading dataset...
2020-08-12 10:06:26,959 : INFO : End of reading dataset...
2020-08-12 10:06:26,960 : INFO : Start of Droping Columns...
2020-08-12 10:06:26,962 : INFO : End of Droping Columns...
2020-08-12 10:06:26,962 : INFO : Start of replacing invalid values...
2020-08-12 10:06:27,030 : INFO : end of replacing invalid values...
2020-08-12 10:06:27,030 : INFO : Start of encode Categorical Values ...
2020-08-12 10:06:27,056 : INFO : end of encode Categorical Values...
2020-08-12 10:06:27,056 : INFO : Start of feature encoding...
2020-08-12 10:06:27,081 : INFO : End of feature encoding...
2020-08-12 10:06:27,086 : INFO : Start of Droping Columns...
2020-08-12 10:06:27,088 : INFO : End of Droping Columns...
2020-08-12 10:06:27,088 : INFO : Start of finding missing values...
2020-08-12 10:06:27,096 : INFO : End of finding missing values...
2020-08-12 10:06:27,097 : INFO : Start of imputing missing values...
2020-08-12 10:06:27,106 : INFO : End of imputing missing values...
2020-08-12 10:06:27,106 : INFO : Start of splitting features and label ...
2020-08-12 10:06:27,107 : INFO : End of splitting features and label ...
2020-08-12 10:06:27,108 : INFO : End of Preprocessing...
2020-08-12 10:06:27,108 : INFO : Start of elbow plotting...
2020-08-12 10:06:27,834 : INFO : The optimum number of clusters is: 3
2020-08-12 10:06:27,834 : INFO : End of elbow plotting...
2020-08-12 10:06:27,834 : INFO : Start of Create clusters...
2020-08-12 10:06:27,870 : INFO : Start of Save Models
2020-08-12 10:06:27,870 : INFO : Start of Save Models
2020-08-12 10:06:27,874 : INFO : Model File KMeans saved
2020-08-12 10:06:27,874 : INFO : Model File KMeans saved
2020-08-12 10:06:27,874 : INFO : End of Save Models
2020-08-12 10:06:27,874 : INFO : End of Save Models
2020-08-12 10:06:27,875 : INFO : succesfully created 3clusters.
2020-08-12 10:06:27,875 : INFO : End of Create clusters...
2020-08-12 10:06:27,883 : INFO : Start of finding best model...
2020-08-12 10:06:27,884 : INFO : Start of finding best params for KNN algo...
2020-08-12 10:06:35,891 : INFO : Knn Forest best params: {'algorithm': 'ball_tree', 'leaf_size': 10, 'n_neighbors': 3, 'p': 1}
2020-08-12 10:06:35,891 : INFO : End of finding best params for knn algo...
2020-08-12 10:06:36,047 : INFO : AUC for knn:0.715646404109589
2020-08-12 10:06:36,048 : INFO : Start of finding best params for randomforest algo...
2020-08-12 10:06:38,309 : INFO : Random Forest best params: {'criterion': 'entropy', 'max_depth': 3, 'max_features': 'auto', 'n_estimators': 5}
2020-08-12 10:06:38,309 : INFO : End of finding best params for randomforest algo...
2020-08-12 10:06:38,312 : INFO : AUC for Random Forest:0.8553082191780822
2020-08-12 10:06:38,312 : INFO : End of finding best model...
2020-08-12 10:06:38,313 : INFO : Start of Save Models
2020-08-12 10:06:38,313 : INFO : Start of Save Models
2020-08-12 10:06:38,314 : INFO : Model File RandomForest0 saved
2020-08-12 10:06:38,314 : INFO : Model File RandomForest0 saved
2020-08-12 10:06:38,314 : INFO : End of Save Models
2020-08-12 10:06:38,314 : INFO : End of Save Models
2020-08-12 10:06:38,317 : INFO : Start of finding best model...
2020-08-12 10:06:38,317 : INFO : Start of finding best params for KNN algo...
2020-08-12 10:06:38,318 : ERROR : Exception raised while finding best params for knn algo:Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=3.
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 108, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_split.py", line 333, in split
    .format(self.n_splits, n_samples))
ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=3.
2020-08-12 10:06:38,320 : ERROR : Exception raised while finding best model:
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 108, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_split.py", line 333, in split
    .format(self.n_splits, n_samples))
ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 185, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 127, in get_best_params_for_KNN
    raise Exception()
Exception
2020-08-12 10:06:38,321 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 108, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_split.py", line 333, in split
    .format(self.n_splits, n_samples))
ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 185, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 127, in get_best_params_for_KNN
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 78, in training_model
    best_model_name, best_model = self.modelTuner.get_best_model(x_train, y_train, x_test, y_test)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 218, in get_best_model
    raise Exception()
Exception
