2020-08-13 18:22:58,779 : INFO : Start of Training
2020-08-13 18:22:58,780 : INFO : Run_id:2020-08-13_182258_491649471
2020-08-13 18:22:58,780 : INFO : Start of Data Load, validation and transformation
2020-08-13 18:22:58,780 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 18:22:58,780 : INFO : End of Archiving Old Rejected Files...
2020-08-13 18:22:58,780 : INFO : Start of Archiving Old Validated Files...
2020-08-13 18:22:58,781 : INFO : End of Archiving Old Validated Files...
2020-08-13 18:22:58,781 : INFO : Start of Archiving Old Processed Files...
2020-08-13 18:22:58,784 : INFO : End of Archiving Old Processed Files...
2020-08-13 18:22:58,784 : INFO : Start of Archiving Old Result Files...
2020-08-13 18:22:59,246 : INFO : End of Archiving Old Result Files...
2020-08-13 18:22:59,247 : INFO : Start of Reading values From Schema...
2020-08-13 18:22:59,250 : INFO : End of Reading values From Schema...
2020-08-13 18:22:59,251 : INFO : Start of Validating Column Length...
2020-08-13 18:22:59,391 : INFO : End of Validating Column Length...
2020-08-13 18:22:59,391 : INFO : Start of Validating Missing Values...
2020-08-13 18:22:59,407 : INFO : End of Validating Missing Values...
2020-08-13 18:22:59,407 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 18:22:59,455 : INFO : Credit_Approval_rename_data.csv: File Transformed successfully!!
2020-08-13 18:22:59,455 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 18:22:59,455 : INFO : Start of Creating Table...
2020-08-13 18:22:59,456 : INFO : Opened training database successfully
2020-08-13 18:22:59,832 : INFO : CREATE TABLE training_raw_data_t column_name
2020-08-13 18:23:00,058 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:00,269 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:00,314 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:00,358 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:00,424 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:00,599 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:00,845 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:01,073 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:01,260 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:01,541 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:01,748 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:01,976 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:02,181 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:02,441 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:02,710 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 18:23:02,718 : INFO : End of Creating Table...
2020-08-13 18:23:02,766 : INFO : Opened training database successfully
2020-08-13 18:23:02,766 : INFO : Start of Inserting Data into Table...
2020-08-13 18:24:46,315 : INFO : End of Inserting Data into Table...
2020-08-13 18:24:46,317 : INFO : Start of Exporting Data into CSV...
2020-08-13 18:24:46,322 : INFO : Opened training database successfully
2020-08-13 18:24:46,379 : INFO : End of Exporting Data into CSV...
2020-08-13 18:24:46,381 : INFO : Start of Moving Processed Files...
2020-08-13 18:24:46,384 : INFO : Moved the already processed file Credit_Approval_rename_data.csv
2020-08-13 18:24:46,384 : INFO : End of Moving Processed Files...
2020-08-13 18:24:46,384 : INFO : End of Data Load, validation and transformation
2020-08-13 18:24:46,385 : INFO : Start of Preprocessing...
2020-08-13 18:24:46,385 : INFO : Start of reading dataset...
2020-08-13 18:24:46,398 : INFO : End of reading dataset...
2020-08-13 18:24:46,398 : INFO : Start of Droping Columns...
2020-08-13 18:24:46,402 : INFO : End of Droping Columns...
2020-08-13 18:24:46,402 : INFO : Start of replacing invalid values...
2020-08-13 18:24:46,449 : INFO : end of replacing invalid values...
2020-08-13 18:24:46,449 : INFO : Start of encode Categorical Values ...
2020-08-13 18:24:46,461 : INFO : end of encode Categorical Values...
2020-08-13 18:24:46,462 : INFO : Start of feature encoding...
2020-08-13 18:24:46,477 : INFO : End of feature encoding...
2020-08-13 18:24:46,480 : INFO : Start of Droping Columns...
2020-08-13 18:24:46,482 : INFO : End of Droping Columns...
2020-08-13 18:24:46,482 : INFO : Start of finding missing values...
2020-08-13 18:24:46,487 : INFO : End of finding missing values...
2020-08-13 18:24:46,487 : INFO : Start of imputing missing values...
2020-08-13 18:24:46,496 : INFO : End of imputing missing values...
2020-08-13 18:24:46,497 : INFO : Start feature selection of dataset...
2020-08-13 18:24:46,498 : ERROR : Exception raised while feature selection of dataset: %sk should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 240, in feature_selection
    data_scores = pd.DataFrame(ordered_feature.scores_, columns=["Score"])
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 348, in fit
    self._check_params(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 514, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.
2020-08-13 18:24:46,500 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 240, in feature_selection
    data_scores = pd.DataFrame(ordered_feature.scores_, columns=["Score"])
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 348, in fit
    self._check_params(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 514, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 341, in preprocess_trainset
    self.X, self.y = self.split_features_label(data1, label_name='Approved')
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 256, in feature_selection
    def split_features_label(self, data, label_name):
Exception
2020-08-13 18:24:46,500 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 240, in feature_selection
    data_scores = pd.DataFrame(ordered_feature.scores_, columns=["Score"])
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 348, in fit
    self._check_params(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 514, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 341, in preprocess_trainset
    self.X, self.y = self.split_features_label(data1, label_name='Approved')
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 256, in feature_selection
    def split_features_label(self, data, label_name):
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 54, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 348, in preprocess_trainset
    def preprocess_predictset(self):
Exception
