2020-08-12 10:19:58,559 : INFO : Start of Training
2020-08-12 10:19:58,560 : INFO : Run_id:2020-08-12_101958_386591291
2020-08-12 10:19:58,560 : INFO : Start of Data Load, validation and transformation
2020-08-12 10:19:58,560 : INFO : Start of Archiving Old Rejected Files...
2020-08-12 10:19:58,560 : INFO : End of Archiving Old Rejected Files...
2020-08-12 10:19:58,560 : INFO : Start of Archiving Old Validated Files...
2020-08-12 10:19:58,563 : INFO : End of Archiving Old Validated Files...
2020-08-12 10:19:58,564 : INFO : Start of Archiving Old Processed Files...
2020-08-12 10:19:58,566 : INFO : End of Archiving Old Processed Files...
2020-08-12 10:19:58,566 : INFO : Start of Archiving Old Result Files...
2020-08-12 10:19:58,567 : INFO : End of Archiving Old Result Files...
2020-08-12 10:19:58,567 : INFO : Start of Reading values From Schema...
2020-08-12 10:19:58,567 : INFO : End of Reading values From Schema...
2020-08-12 10:19:58,567 : INFO : Start of Validating Column Length...
2020-08-12 10:19:58,567 : INFO : End of Validating Column Length...
2020-08-12 10:19:58,567 : INFO : Start of Validating Missing Values...
2020-08-12 10:19:58,568 : INFO : End of Validating Missing Values...
2020-08-12 10:19:58,568 : INFO : Start of Replacing Missing Values with NULL...
2020-08-12 10:19:58,568 : INFO : End of Replacing Missing Values with NULL...
2020-08-12 10:19:58,568 : INFO : Start of Creating Table...
2020-08-12 10:19:58,568 : INFO : Opened training database successfully
2020-08-12 10:19:58,569 : INFO : Tables created successfully
2020-08-12 10:19:58,569 : INFO : Closed training database successfully
2020-08-12 10:19:58,569 : INFO : End of Creating Table...
2020-08-12 10:19:58,570 : INFO : Opened training database successfully
2020-08-12 10:19:58,570 : INFO : Start of Inserting Data into Table...
2020-08-12 10:19:58,570 : INFO : End of Inserting Data into Table...
2020-08-12 10:19:58,570 : INFO : Start of Exporting Data into CSV...
2020-08-12 10:19:58,571 : INFO : Opened training database successfully
2020-08-12 10:19:58,582 : INFO : End of Exporting Data into CSV...
2020-08-12 10:19:58,583 : INFO : Start of Moving Processed Files...
2020-08-12 10:19:58,583 : INFO : End of Moving Processed Files...
2020-08-12 10:19:58,583 : INFO : End of Data Load, validation and transformation
2020-08-12 10:19:58,583 : INFO : Start of Preprocessing...
2020-08-12 10:19:58,583 : INFO : Start of reading dataset...
2020-08-12 10:19:58,591 : INFO : End of reading dataset...
2020-08-12 10:19:58,591 : INFO : Start of Droping Columns...
2020-08-12 10:19:58,593 : INFO : End of Droping Columns...
2020-08-12 10:19:58,593 : INFO : Start of replacing invalid values...
2020-08-12 10:19:58,630 : INFO : end of replacing invalid values...
2020-08-12 10:19:58,630 : INFO : Start of encode Categorical Values ...
2020-08-12 10:19:58,642 : INFO : end of encode Categorical Values...
2020-08-12 10:19:58,642 : INFO : Start of feature encoding...
2020-08-12 10:19:58,658 : INFO : End of feature encoding...
2020-08-12 10:19:58,660 : INFO : Start of Droping Columns...
2020-08-12 10:19:58,662 : INFO : End of Droping Columns...
2020-08-12 10:19:58,662 : INFO : Start of finding missing values...
2020-08-12 10:19:58,669 : INFO : End of finding missing values...
2020-08-12 10:19:58,670 : INFO : Start of imputing missing values...
2020-08-12 10:19:58,676 : INFO : End of imputing missing values...
2020-08-12 10:19:58,676 : INFO : Start of splitting features and label ...
2020-08-12 10:19:58,677 : INFO : End of splitting features and label ...
2020-08-12 10:19:58,677 : INFO : End of Preprocessing...
2020-08-12 10:19:58,678 : INFO : Start of elbow plotting...
2020-08-12 10:19:59,461 : INFO : The optimum number of clusters is: 3
2020-08-12 10:19:59,461 : INFO : End of elbow plotting...
2020-08-12 10:19:59,462 : INFO : Start of Create clusters...
2020-08-12 10:19:59,527 : INFO : Start of Save Models
2020-08-12 10:19:59,527 : INFO : Start of Save Models
2020-08-12 10:19:59,531 : INFO : Model File KMeans saved
2020-08-12 10:19:59,531 : INFO : Model File KMeans saved
2020-08-12 10:19:59,531 : INFO : End of Save Models
2020-08-12 10:19:59,531 : INFO : End of Save Models
2020-08-12 10:19:59,532 : INFO : succesfully created 3clusters.
2020-08-12 10:19:59,532 : INFO : End of Create clusters...
2020-08-12 10:19:59,540 : INFO : Start of finding best model...
2020-08-12 10:19:59,540 : INFO : Start of finding best params for KNN algo...
2020-08-12 10:20:04,938 : ERROR : Exception raised while finding best params for knn algo:'n_neighbors'
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 116, in get_best_params_for_KNN
    self.n_neighbors = self.grid.best_params_['n_neighbors']
KeyError: 'n_neighbors'
2020-08-12 10:20:04,939 : ERROR : Exception raised while finding best model:
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 116, in get_best_params_for_KNN
    self.n_neighbors = self.grid.best_params_['n_neighbors']
KeyError: 'n_neighbors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 188, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 130, in get_best_params_for_KNN
    raise Exception()
Exception
2020-08-12 10:20:04,939 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 116, in get_best_params_for_KNN
    self.n_neighbors = self.grid.best_params_['n_neighbors']
KeyError: 'n_neighbors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 188, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 130, in get_best_params_for_KNN
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 78, in training_model
    best_model_name, best_model = self.modelTuner.get_best_model(x_train, y_train, x_test, y_test)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 221, in get_best_model
    raise Exception()
Exception
