2020-08-13 11:29:40,593 : INFO : Start of Training
2020-08-13 11:29:40,593 : INFO : Run_id:2020-08-13_112940_371160808
2020-08-13 11:29:40,593 : INFO : Start of Data Load, validation and transformation
2020-08-13 11:29:40,593 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 11:29:40,594 : INFO : End of Archiving Old Rejected Files...
2020-08-13 11:29:40,594 : INFO : Start of Archiving Old Validated Files...
2020-08-13 11:29:40,594 : INFO : End of Archiving Old Validated Files...
2020-08-13 11:29:40,594 : INFO : Start of Archiving Old Processed Files...
2020-08-13 11:29:40,596 : INFO : End of Archiving Old Processed Files...
2020-08-13 11:29:40,596 : INFO : Start of Archiving Old Result Files...
2020-08-13 11:29:40,597 : INFO : End of Archiving Old Result Files...
2020-08-13 11:29:40,597 : INFO : Start of Reading values From Schema...
2020-08-13 11:29:40,597 : INFO : End of Reading values From Schema...
2020-08-13 11:29:40,598 : INFO : Start of Validating Column Length...
2020-08-13 11:29:40,607 : INFO : End of Validating Column Length...
2020-08-13 11:29:40,607 : INFO : Start of Validating Missing Values...
2020-08-13 11:29:40,619 : INFO : End of Validating Missing Values...
2020-08-13 11:29:40,619 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 11:29:40,651 : INFO : Credit_Approval_rename_data.csv: File Transformed successfully!!
2020-08-13 11:29:40,651 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 11:29:40,651 : INFO : Start of Creating Table...
2020-08-13 11:29:40,652 : INFO : Opened training database successfully
2020-08-13 11:29:40,850 : INFO : CREATE TABLE training_raw_data_t column_name
2020-08-13 11:29:40,956 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,060 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,164 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,292 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,397 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,513 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,631 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,736 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,840 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:41,961 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:42,118 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:42,241 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:42,384 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:42,521 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:42,627 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:29:42,627 : INFO : End of Creating Table...
2020-08-13 11:29:42,628 : INFO : Opened training database successfully
2020-08-13 11:29:42,629 : INFO : Start of Inserting Data into Table...
2020-08-13 11:31:09,317 : INFO : End of Inserting Data into Table...
2020-08-13 11:31:09,318 : INFO : Start of Exporting Data into CSV...
2020-08-13 11:31:09,322 : INFO : Opened training database successfully
2020-08-13 11:31:09,368 : INFO : End of Exporting Data into CSV...
2020-08-13 11:31:09,371 : INFO : Start of Moving Processed Files...
2020-08-13 11:31:09,376 : INFO : Moved the already processed file Credit_Approval_rename_data.csv
2020-08-13 11:31:09,377 : INFO : End of Moving Processed Files...
2020-08-13 11:31:09,378 : INFO : End of Data Load, validation and transformation
2020-08-13 11:31:09,378 : INFO : Start of Preprocessing...
2020-08-13 11:31:09,379 : INFO : Start of reading dataset...
2020-08-13 11:31:09,408 : INFO : End of reading dataset...
2020-08-13 11:31:09,409 : INFO : Start of Droping Columns...
2020-08-13 11:31:09,417 : INFO : End of Droping Columns...
2020-08-13 11:31:09,417 : INFO : Start of replacing invalid values...
2020-08-13 11:31:09,526 : INFO : end of replacing invalid values...
2020-08-13 11:31:09,527 : INFO : Start of encode Categorical Values ...
2020-08-13 11:31:09,538 : INFO : end of encode Categorical Values...
2020-08-13 11:31:09,538 : INFO : Start of feature encoding...
2020-08-13 11:31:09,567 : INFO : End of feature encoding...
2020-08-13 11:31:09,570 : INFO : Start of Droping Columns...
2020-08-13 11:31:09,573 : INFO : End of Droping Columns...
2020-08-13 11:31:09,573 : INFO : Start of finding missing values...
2020-08-13 11:31:09,581 : INFO : End of finding missing values...
2020-08-13 11:31:09,582 : INFO : Start of imputing missing values...
2020-08-13 11:31:09,593 : INFO : End of imputing missing values...
2020-08-13 11:31:09,593 : INFO : Start feature selection of dataset...
2020-08-13 11:31:09,620 : ERROR : Exception raised while feature selection of dataset: %sk should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 240, in feature_selection
    ordered_feature = ordered_rank_features.fit(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 348, in fit
    self._check_params(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 514, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.
2020-08-13 11:31:09,816 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 240, in feature_selection
    ordered_feature = ordered_rank_features.fit(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 348, in fit
    self._check_params(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 514, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 341, in preprocess_trainset
    data1 = self.feature_selection(data)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 256, in feature_selection
    raise Exception()
Exception
2020-08-13 11:31:09,818 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 240, in feature_selection
    ordered_feature = ordered_rank_features.fit(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 348, in fit
    self._check_params(X, y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\feature_selection\_univariate_selection.py", line 514, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 11; got 15. Use k='all' to return all features.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 341, in preprocess_trainset
    data1 = self.feature_selection(data)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 256, in feature_selection
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 54, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 348, in preprocess_trainset
    raise Exception
Exception
